### ISSUE TITLE
Fix error when series not found in Sonarr

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/sonarr-episode-prune#1]
The script errors when the series is not in Sonarr, for example:

```bash
python sonarr-episode-prune.py
```

```
2020-01-21 01:30:33 Sonarr Episode Prune INFO     Checking series american-experience for any episodes to delete
Traceback (most recent call last):
  File "sonarr-episode-prune.py", line 172, in <module>
    cli()
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "sonarr-episode-prune.py", line 101, in cli
    clean_series(all_series[show]['id'])
KeyError: 'american-experience'
```

**Comment by onedr0p** [comment]
Project appears dead, closing.
